from enum import StrEnum
class AcquisitionState(StrEnum):
    NOT_ATTEMPTED='NOT_ATTEMPTED'; AUTO_FETCHING='AUTO_FETCHING'; AUTO_SUCCESS='AUTO_SUCCESS'; DNS_FAILURE='DNS_FAILURE'; NETWORK_FAILURE='NETWORK_FAILURE'; ACCESS_BLOCKED='ACCESS_BLOCKED'; MANUAL_PENDING='MANUAL_PENDING'; MANUAL_IMPORTED='MANUAL_IMPORTED'; PARSE_SUCCESS='PARSE_SUCCESS'; PARSE_FAILED='PARSE_FAILED'; VALIDATED='VALIDATED'; PUBLISHED='PUBLISHED'
